# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file: gitlab-templates/blocks/workflow.yml

publish-to-flathub:
  stage: publish
  image: invent-registry.kde.org/sysadmin/ci-images/flatpak-builder:latest
  tags:
    - Linux
  rules:
    - if: $CI_PROJECT_PATH == "packaging/flatpak-kde-runtime" && $CI_COMMIT_REF_PROTECTED == "true"
      when: manual
  variables:
    FLAT_MANAGER_ADDRESS: https://hub.flathub.org/
    RELEASE_CHANNEL: stable
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
  script:
    # Trigger publishing to Flathub
    - flat-manager-client -v create "$FLAT_MANAGER_ADDRESS" "${RELEASE_CHANNEL}" --build-log-url ${CI_PIPELINE_URL} > publish_build.txt
    - flat-manager-client -v commit --end-of-life="We strongly recommend moving to the latest stable version of the Platform and SDK" --wait "$(cat publish_build.txt)
    - flat-manager-client -v publish --wait "$(cat publish_build.txt)"
