# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

workflow:
  rules:
    # Prevent branch pipelines if an MR is open on the branch.
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Allow merge request pipelines.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Build tags and branches too
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

flatpak:
  image: invent-registry.kde.org/sysadmin/ci-images/flatpak-builder:latest
  tags:
    - Linux
  interruptible: true
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
  script:
    - echo ${KDE_FLATPAK_MODULE_NAME}
    - echo ${KDE_FLATPAK_APP_ID}
    # Lint manifest
    # flatpak run --command=flatpak-builder-lint org.flatpak.Builder org.kde.Sdk.json.in
    - json-glib-validate org.kde.Sdk.json.in
    - json-glib-validate org.freedesktop.Platform.Icontheme.Adwaita.json
    - json-glib-validate flathub.json

build-runtime:
  stage: build
  when: manual
  image: invent-registry.kde.org/sysadmin/ci-images/flatpak-builder:latest
  tags:
    - Linux
  script:
    - export ARCH=x86_64
    - sed "s,@@SDK_ARCH@@,${ARCH},g" org.kde.Sdk.json.in > org.kde.Sdk.json
    - flatpak-builder --install-deps-from=flathub --user --disable-rofiles-fuse --arch=x86_64 --force-clean --require-changes --ccache --repo=repo --subject="build of org.kde.Sdk, `date` $(`git rev-parse HEAD`)" sdk org.kde.Sdk.json
