# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file: gitlab-templates/blocks/workflow.yml

lint-manifests:
  stage: validate
  image: storage.kde.org/vm-images/buildstream
  tags:
    - VM
    - amd64
  interruptible: true
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
  script:
    #- flatpak run --command=flatpak-builder-lint org.flatpak.Builder org.kde.Sdk.json.in
    - json-glib-validate org.kde.Sdk.json.in
    - appstreamcli validate --no-net org.kde.{Sdk,Platform}.metainfo.xml

.build-runtime:
  stage: build
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  when: manual
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
  script:
    - make elements/org.kde.Sdk.bst
    - bst build flatpak-images/flatpak-runtimes.bst
    - bst artifact checkout flatpak-images/flatpak-runtimes.bst --directory checkout/repo-$ARCH/
    - cp org.kde.Sdk.json checkout/repo-$ARCH/
    - mkdir artifacts/
    - tar czf artifacts/repository-$ARCH.tar.gz -C checkout/ repo-$ARCH/
    - python3 ci-utilities/sync-s3-folder.py --mode upload --verbose --local ./artifacts/ --remote storage.kde.org/ci-artifacts/$CI_PROJECT_PATH/p/$CI_PIPELINE_ID/

build-runtime-amd64:
  extends: .build-runtime
  image: storage.kde.org/vm-images/buildstream
  tags:
    - LargeVM
    - amd64
  variables:
    ARCH: x86_64

build-runtime-arm64:
  extends: .build-runtime
  image: storage.kde.org/vm-images/buildstream-arm64
  tags:
    - LargeVM
    - arm64
  variables:
    ARCH: aarch64

publish-to-flathub:
  stage: publish
  image: invent-registry.kde.org/sysadmin/ci-images/flatpak-builder:latest
  tags:
    - Linux
  needs:
    - build-runtime-amd64
    - build-runtime-arm64
  rules:
    - if: $CI_PROJECT_PATH == "packaging/flatpak-kde-runtime" && $CI_COMMIT_REF_PROTECTED == "true"
      when: manual
  variables:
    FLAT_MANAGER_ADDRESS: https://hub.flathub.org/
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
  script:
    # Bring in the artifacts
    - mkdir artifacts/
    - python3 ci-utilities/sync-s3-folder.py --mode download --verbose --local ./artifacts/ --remote storage.kde.org/ci-artifacts/$CI_PROJECT_PATH/p/$CI_PIPELINE_ID/
    - tar -xf ./artifacts/repository-x86_64.tar.gz
    - tar -xf ./artifacts/repository-aarch64.tar.gz
    # Combine them into a single repository
    - ostree init --repo=repo-combined --mode archive-z2
    - for ref in $(ostree --repo=repo-x86_64 refs); do
        flatpak build-commit-from --no-update-summary --disable-fsync --src-repo=repo-x86_64 repo-combined "$ref";
      done
    - for ref in $(ostree --repo=repo-aarch64 refs); do
        flatpak build-commit-from --no-update-summary --disable-fsync --src-repo=repo-aarch64 repo-combined "$ref";
      done
    - flatpak build-update-repo --generate-static-deltas --static-delta-ignore-ref=*.Debug --static-delta-ignore-ref=*.Sources repo-combined
    - |
      SDK_BRANCH="$(jq -r '.branch' org.kde.Sdk.json.in)"
      case "${SDK_BRANCH}" in
        *-beta) RELEASE_CHANNEL=beta ;;
        *) RELEASE_CHANNEL=stable ;;
      esac
      export RELEASE_CHANNEL
      echo "Publishing branch ${SDK_BRANCH} to Flathub channel ${RELEASE_CHANNEL}"
    # Trigger publishing to Flathub
    - flat-manager-client -v create "$FLAT_MANAGER_ADDRESS" "${RELEASE_CHANNEL}" --build-log-url ${CI_PIPELINE_URL} > publish_build.txt
    - flat-manager-client push --all-objects "$(cat publish_build.txt)" repo-combined --build-log-url ${CI_PIPELINE_URL}
    - flat-manager-client -v commit --wait "$(cat publish_build.txt)"
    - flat-manager-client -v publish --wait "$(cat publish_build.txt)"
    - echo "Check https://hub.flathub.org/status to see when this is going to be available"
