#!/bin/sh

cat <<EOF > Makefile
all:

install:
	mkdir -p ${DESTDIR}/usr/lib
	install os-release ${DESTDIR}/usr/lib
	mkdir -p ${DESTDIR}/usr/share/appdata
	mkdir -p ${DESTDIR}/etc
	install issue ${DESTDIR}/etc
	install issue.net ${DESTDIR}/etc
	install org.kde.Platform.appdata.xml ${DESTDIR}/usr/share/appdata
	install org.kde.Sdk.appdata.xml ${DESTDIR}/usr/share/appdata
	appstream-compose --basename=org.kde.Platform --prefix=/usr --origin=flatpak org.kde.Platform
	appstream-compose --basename=org.kde.Sdk --prefix=/usr --origin=flatpak org.kde.Sdk
	sed -i 's@set(_qt5_module_paths ${_qt5_install_prefix})@set(_qt5_module_paths ${_qt5_install_prefix} /app/lib/${CMAKE_CXX_LIBRARY_ARCHITECTURE}/cmake)@' /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5ModuleLocation.cmake,
EOF
