#!/bin/sh

cat <<EOF > Makefile
all:

install:
	mkdir -p ${DESTDIR}/usr/lib
	install os-release ${DESTDIR}/usr/lib
	mkdir -p ${DESTDIR}/usr/share/appdata
	install org.kde.Platform.appdata.xml ${DESTDIR}/usr/share/appdata
	install org.kde.Sdk.appdata.xml ${DESTDIR}/usr/share/appdata
	appstream-compose --basename=org.kde.Platform --prefix=/usr --origin=flatpak org.kde.Platform
	appstream-compose --basename=org.kde.Sdk --prefix=/usr --origin=flatpak org.kde.Sdk
EOF
