# SPDX-FileCopyrightText: 2025 Aleix Pol Gonzalez <aleix.pol@codethink.co.uk>
# SPDX-License-Identifier: MIT

# Unique project name
name: kde

# Required BuildStream version
min-version: 2.5

# Subdirectory where elements are stored
element-path: elements

(@):
- freedesktop-sdk.bst:include/runtime.yml
- include/aliases.yml

# Options to specify for the project, these provide
# command line switches which control the behavior of
# conditional directives in the element.bst files.
#
options:
  arch:
    type: arch
    description: CPU Architecture
    variable: arch
    values:
    - aarch64
    - x86_64
    - riscv64

sandbox:
  build-arch: '%{arch}'

variables:
  branch: 'qt6.10' # TODO switch with Qt's version!
  strip-binaries: ''

environment:
# These need getting set so that projects can run tools and not get weird warnings.
# trigger to adding this was qca's usage of qmake -query (which in turn comes from Qt upstream)
  LANG: C.UTF-8
  LC_ALL: C.UTF-8

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  elements:
  - autotools
  - meson
  - cmake
  - make
  sources:
  - patch
  - git

- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  elements:
  - pyproject
  - flatpak_image
  - flatpak_repo
  - collect_manifest
  - collect_integration
  sources:
  - git_repo
  - zip

- origin: junction
  junction: freedesktop-sdk.bst
  elements:
  - collect_initial_scripts


sources:
  git_repo:
    config:
      ref-format: git-describe

artifacts:
- url: https://cache.freedesktop-sdk.io:11001
  type: all
  push: false
- url: http://91.98.33.57:50051
  push: true
  connection-config:
    keepalive-time: 60

source-caches:
- url: https://cache.freedesktop-sdk.io:11001
  type: all
  push: false

