kind: stack
description: Stack of components in the Plasma Desktop

depends:
- plasma/breeze.bst
- plasma/plasma-integration.bst
- plasma/kwayland-integration.bst

### can't find these ones in the org.kde.Sdk.json.in manifest, haven't incorporated them (yet)
#- filename: plasma/bluedevil.bst
#- filename: plasma/discover.bst
#- filename: plasma/kactivitymanagerd.bst
#- filename: plasma/kde-cli-tools.bst
#- filename: plasma/kdecoration.bst
#- filename: plasma/kscreen.bst
#- filename: plasma/kscreenlocker.bst
#- filename: plasma/ksysguard.bst
#- filename: plasma/kwin.bst
#- filename: plasma/libkscreen.bst
#- filename: plasma/libksysguard.bst
#- filename: plasma/milou.bst
#- filename: plasma/plasma-mobile.bst
#- filename: plasma/plasma-nm.bst
#- filename: plasma/plasma-pa.bst
#- filename: plasma/plasma-phone-components.bst
#- filename: plasma/plasma-phone-components_git.bst
#- filename: plasma/plasma-settings.bst
#- filename: plasma/plasma-settings_git.bst
#- filename: plasma/plasma-workspace.bst
#- filename: plasma/polkit-kde-agent-1.bst
#- filename: plasma/powerdevil.bst
#- filename: plasma/systemsettings.bst
#- filename: plasma/xdg-desktop-portal-kde.bst
