#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Aleix Pol Gonzalez <aleix.pol@kde.org>
# SPDX-License-Identifier: MIT

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass

import yaml


QT_DEPENDENCIES_URL = (
    "https://code.qt.io/cgit/qt/{repo}.git/plain/dependencies.yaml?h={ref}"
)
KDE_DEPENDENCIES_URL = (
    "https://invent.kde.org/sysadmin/repo-metadata/-/raw/master/"
    "dependencies/dependency-data-kf6-qt6"
)
USER_AGENT = "flatpak-kde-runtime trim-dependencies/1.0"


@dataclass(frozen=True)
class ManagedModule:
    kind: str
    key: str
    element_ref: str
    path: pathlib.Path
    version: str | None = None
    upstream_ref: str | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Trim over-broad BuildStream build-depends using upstream Qt and KDE "
            "dependency metadata."
        )
    )
    parser.add_argument(
        "element_dir",
        nargs="?",
        default="elements/org.kde.Sdk",
        help="Directory containing generated .bst elements to trim",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned changes without modifying files",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print extra diagnostics",
    )
    return parser.parse_args()


def fetch_text(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request) as response:
        return response.read().decode("utf-8")


def find_elements_root(path: pathlib.Path) -> pathlib.Path:
    resolved = path.resolve()
    for candidate in [resolved, *resolved.parents]:
        if candidate.name == "elements":
            return candidate
    raise ValueError(f"Unable to find elements/ ancestor for {path}")


def load_yaml(path: pathlib.Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    return data if isinstance(data, dict) else {}


def dump_yaml(path: pathlib.Path, data: dict) -> None:
    header = "# File generated by trim-dependencies.py\n\n"
    with path.open("w", encoding="utf-8") as handle:
        handle.write(header)
        yaml.dump(
            data,
            handle,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )


def qt_identity(source_url: str) -> tuple[str, str] | None:
    match = re.search(
        r"/submodules/(?P<repo>[^/]+?)-everywhere-src-(?P<version>[^/]+)\.",
        source_url,
    )
    if not match:
        return None
    return match.group("repo"), match.group("version")


def kde_identity(source_url: str) -> str | None:
    if not source_url.startswith("kde:"):
        return None
    project = source_url.removeprefix("kde:")
    if project.endswith(".git"):
        project = project[:-4]
    return project


def module_from_file(path: pathlib.Path, elements_root: pathlib.Path) -> ManagedModule | None:
    resolved_path = path.resolve()
    data = load_yaml(path)
    for source in data.get("sources", []):
        if not isinstance(source, dict):
            continue
        source_url = source.get("url")
        if not isinstance(source_url, str):
            continue
        qt = qt_identity(source_url)
        if qt:
            repo, version = qt
            return ManagedModule(
                kind="qt",
                key=repo,
                version=version,
                upstream_ref=version,
                element_ref=str(resolved_path.relative_to(elements_root)),
                path=resolved_path,
            )
        kde = kde_identity(source_url)
        if kde:
            return ManagedModule(
                kind="kde",
                key=kde,
                element_ref=str(resolved_path.relative_to(elements_root)),
                path=resolved_path,
            )
    return None


def discover_modules(element_dir: pathlib.Path, elements_root: pathlib.Path) -> list[ManagedModule]:
    modules: list[ManagedModule] = []
    for path in sorted(element_dir.rglob("*.bst")):
        module = module_from_file(path, elements_root)
        if module:
            modules.append(module)
    return modules


class QtDependencyResolver:
    def __init__(self, verbose: bool):
        self.verbose = verbose
        self.cache: dict[tuple[str, str], set[str]] = {}

    def dependencies_for(self, module: ManagedModule) -> set[str] | None:
        if module.upstream_ref is None:
            return None
        cache_key = (module.key, module.upstream_ref)
        if cache_key not in self.cache:
            self.cache[cache_key] = self._fetch_dependencies(module.key, module.upstream_ref)
        return self.cache[cache_key]

    def _fetch_dependencies(self, repo: str, upstream_ref: str) -> set[str]:
        candidates = [upstream_ref]
        if "." in upstream_ref:
            branch_candidate = ".".join(upstream_ref.split(".")[:2])
            if branch_candidate not in candidates:
                candidates.append(branch_candidate)

        last_error: Exception | None = None
        for candidate in candidates:
            try:
                text = fetch_text(QT_DEPENDENCIES_URL.format(repo=repo, ref=candidate))
                payload = yaml.safe_load(text) or {}
                result: set[str] = set()
                for dep_path, details in payload.get("dependencies", {}).items():
                    if not isinstance(dep_path, str) or not isinstance(details, dict):
                        continue
                    result.add(pathlib.PurePosixPath(dep_path).name)
                return result
            except (urllib.error.URLError, urllib.error.HTTPError, yaml.YAMLError) as err:
                last_error = err
        if last_error and self.verbose:
            print(f"warning: failed to fetch Qt dependencies for {repo}: {last_error}", file=sys.stderr)
        raise RuntimeError(f"Unable to fetch Qt dependencies for {repo}")


class KdeDependencyResolver:
    def __init__(self):
        self.cache: dict[str, set[str]] | None = None

    def dependencies_for(self, module: ManagedModule) -> set[str]:
        if self.cache is None:
            self.cache = self._fetch_dependencies()
        return self.cache.get(module.key, set())

    def _fetch_dependencies(self) -> dict[str, set[str]]:
        text = fetch_text(KDE_DEPENDENCIES_URL)
        mapping: dict[str, set[str]] = {}
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or ":" not in stripped:
                continue
            project, dependency = stripped.split(":", maxsplit=1)
            project = project.strip()
            dependency = dependency.strip()
            if not project or not dependency:
                continue
            mapping.setdefault(project, set()).add(dependency)
        return mapping


def rewrite_dependencies(
    module: ManagedModule,
    managed_refs: set[str],
    qt_map: dict[str, str],
    kde_map: dict[str, str],
    qt_resolver: QtDependencyResolver | None,
    kde_resolver: KdeDependencyResolver | None,
    dry_run: bool,
    verbose: bool,
) -> bool:
    data = load_yaml(module.path)
    current_deps = data.get("build-depends")
    if not isinstance(current_deps, list):
        return False

    qt_refs = set(qt_map.values())
    kde_refs = set(kde_map.values())
    direct_managed_refs: set[str] = set()
    preserved_managed_refs: set[str] = set()
    if module.kind == "qt" and qt_resolver is not None:
        upstream_deps = qt_resolver.dependencies_for(module)
        if upstream_deps is None:
            return False
        direct_managed_refs = {
            qt_map[dep] for dep in upstream_deps if dep in qt_map and qt_map[dep] != module.element_ref
        }
    elif module.kind == "kde" and kde_resolver is not None:
        upstream_deps = kde_resolver.dependencies_for(module)
        direct_managed_refs = {
            kde_map[dep] for dep in upstream_deps if dep in kde_map and kde_map[dep] != module.element_ref
        }
        preserved_managed_refs = {dep for dep in current_deps if dep in qt_refs}
    else:
        return False

    preserved = [dep for dep in current_deps if dep not in managed_refs or dep in preserved_managed_refs]
    ordered_direct = [dep for dep in current_deps if dep in direct_managed_refs and dep not in preserved]
    for dep in sorted(direct_managed_refs):
        if dep not in ordered_direct:
            ordered_direct.append(dep)

    new_deps = preserved + ordered_direct
    if new_deps == current_deps:
        if verbose:
            print(f"unchanged {module.element_ref}")
        return False

    data["build-depends"] = new_deps
    if dry_run:
        print(f"{module.element_ref}:")
        print(f"  old: {len(current_deps)} deps")
        print(f"  new: {len(new_deps)} deps")
        if verbose:
            print(f"  kept: {new_deps}")
    else:
        dump_yaml(module.path, data)
        print(f"updated {module.element_ref}: {len(current_deps)} -> {len(new_deps)} deps")
    return True


def main() -> int:
    args = parse_args()
    element_dir = pathlib.Path(args.element_dir)
    if not element_dir.exists():
        print(f"error: {element_dir} does not exist", file=sys.stderr)
        return 1

    elements_root = find_elements_root(element_dir)
    modules = discover_modules(element_dir, elements_root)
    if not modules:
        print(f"error: no managed Qt/KDE elements found under {element_dir}", file=sys.stderr)
        return 1

    qt_map = {module.key: module.element_ref for module in modules if module.kind == "qt"}
    kde_map = {module.key: module.element_ref for module in modules if module.kind == "kde"}
    managed_refs = {module.element_ref for module in modules}

    qt_resolver = QtDependencyResolver(args.verbose)
    kde_resolver = KdeDependencyResolver()

    updated = 0
    for module in modules:
        try:
            changed = rewrite_dependencies(
                module=module,
                managed_refs=managed_refs,
                qt_map=qt_map,
                kde_map=kde_map,
                qt_resolver=qt_resolver,
                kde_resolver=kde_resolver,
                dry_run=args.dry_run,
                verbose=args.verbose,
            )
        except RuntimeError as err:
            print(f"warning: {module.element_ref}: {err}", file=sys.stderr)
            continue
        if changed:
            updated += 1

    summary = "would update" if args.dry_run else "updated"
    print(f"{summary} {updated} element(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
